analyze_and_test:
  stage: analyze_and_test
  image: cirrusci/flutter:stable
  before_script:
    - export PATH="$PATH":"$HOME/.flutter-sdk/.pub-cache/bin"
    - flutter pub get
  script:
    - flutter analyze
    - flutter test
