image: cirrusci/flutter:stable

cache:
  paths:
    - .pub-cache/global_packages

stages:
  - analyze_and_test

before_script:
  - export PATH="$PATH":"$HOME/.flutter-sdk/.pub-cache/bin"
  - flutter pub get

analyze_and_test:
  stage: analyze_and_test
  script:
    - flutter analyze
    - flutter test
  tags:
    - main
  only:
    - merge_requests
