name: podedex
description: A Flutter application that allows interacting with Pokemons.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  flutter_native_splash: ^2.0.5
  flutter_launcher_icons: ^0.9.2
#  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true


#--------------- SPLASH SCREEN ----------------#

flutter_native_splash:
  color: "#3558CD"
  image: assets/images/logo.png
  fullscreen: true


#--------------- FLUTTER LAUNCHER ICONS ---------------#

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#4F72E5"
  adaptive_icon_foreground: "assets/images/adaptative_app_icon.png"